obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.2 # distance a circular robot should be clear of the obstacle

inflation_radius: 0.3  # max. distance from an obstacle at which costs are incurred for planning paths.
cost_scaling_factor: 1.5  # exponential rate at which the obstacle cost drops off (default: 10)

max_obstacle_height: 0.6
min_obstacle_height: 0.0

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /vehicle/laser/scan, marking: true, clearing: true}
