GlobalPlanner:
  
  old_navfn_behavoir: false
  use_quadratic: true
  use_dijkstra: true
  use_grid_path: false
  visualize_potential: true
  
  allow_unknown: true

  planner_window_x: 0.0
  planner_window_y: 0.0
  default_tolerance: 0.05

  publish_scale: 100
  planner_costmap_publish_frecuency: 0.2

  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
