# static_map - True if using existing map
global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  resolution: 0.02
  width: 10.0
  height: 10.0
  #plugins:
  #  - {name: map_layer, type: "costmap_2d::StaticLayer"}
  #  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
  #  - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}
