# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.0
  rolling_window: false
  resolution: 0.01
  static_map: true
  width: 10.0
  height: 10.0
  transform_tolerance: 0.5
