# local planner 
base_local_planner: "dwa_local_planner/DWAPlannerROS"
# global planner 
base_global_planner: "global_planner/GlobalPlanner"

recovery_behaviors: [{
    name: conservative_reset, 
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery1,
    type: rotate_recovery/RotateRecovery
  }, {
    name: aggressive_reset,
    type: clear_costmap_recovery/ClearCostmapRecovery
  }, {
    name: rotate_recovery2,
    type: rotate_recovery/RotateRecovery}]


recovery_behavoir_enabled: true
clearing_rotation_allowed: true

shutdown_costmaps: false

controller_frequency: 3.0
controller_patience: 10.0

planner_frequency: 1.0
planner_patience: 15.0

oscillation_timeout: 0.0
oscillation_distance: 0.5
conservative_reset_dist: 3.0


# Global Plan Parameters
prune_plan:                 true