# local planner 
base_local_planner: "dwa_local_planner/DWAPlannerROS"
# global planner 
base_global_planner: "global_planner/GlobalPlanner"


recovery_behavoir_enabled: true
clearing_rotation_allowed: false

shutdown_costmaps: false

controller_frequency: 3.0
controller_patience: 10.0

planner_frequency: 0.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.5
conservative_reset_dist: 3.0


# Global Plan Parameters
prune_plan:                 true

recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'move_slow_and_clear'
    type: 'move_slow_and_clear/MoveSlowAndClear'

super_conservative_reset:
  reset_distance: 5.0

conservative_reset:
  reset_distance: 3.0

aggressive_reset:
  reset_distance: 1.84

move_slow_and_clear:
  clearing_distance: 0.5
  limited_trans_speed: 0.25
  limited_rot_speed: 0.45
  limited_distance: 0.3