(cl:defpackage costum_msgs-msg
  (:use )
  (:export
   "<GLOBALSEGMENTRESULTSMSG>"
   "GLOBALSEGMENTRESULTSMSG"
   "<GLOBALSIMULATIONRESULTSMSG>"
   "GLOBALSIMULATIONRESULTSMSG"
   "<GOALINFO>"
   "GOALINFO"
   "<INDIVIDUALITERATIONRESULTSMSG>"
   "INDIVIDUALITERATIONRESULTSMSG"
   "<INDIVIDUALSEGMENTRESULTSMSG>"
   "INDIVIDUALSEGMENTRESULTSMSG"
   "<PATHINFO>"
   "PATHINFO"
   "<ROUTETIMES>"
   "ROUTETIMES"
   "<SIMULATIONMETADATAMSG>"
   "SIMULATIONMETADATAMSG"
   "<SIMULATIONMSG>"
   "SIMULATIONMSG"
  ))

