(cl:in-package costum_msgs-msg)
(cl:export '(PLAN_FILE-VAL
          PLAN_FILE
          DATE-VAL
          DATE
          SIMULATIONS-VAL
          SIMULATIONS
          GLOBAL_TIME_AVERAGE-VAL
          GLOBAL_TIME_AVERAGE
          GLOBAL_DISTANCE_AVERAGE-VAL
          GLOBAL_DISTANCE_AVERAGE
          GLOBAL_VELOCITY_AVERAGE-VAL
          GLOBAL_VELOCITY_AVERAGE
          GLOBAL_LINEAR_VELOCITY_AVERAGE-VAL
          GLOBAL_LINEAR_VELOCITY_AVERAGE
          GLOBAL_MAXIMUM_LINEAR_VELOCITY-VAL
          GLOBAL_MAXIMUM_LINEAR_VELOCITY
          GLOBAL_FAILURES-VAL
          GLOBAL_FAILURES
          GLOBAL_PLANNER-VAL
          GLOBAL_PLANNER
          LOCAL_PLANNER-VAL
          LOCAL_PLANNER
          SECTIONS-VAL
          SECTIONS
))