(cl:in-package costum_msgs-msg)
(cl:export '(ID-VAL
          ID
          TIME_AVERAGE-VAL
          TIME_AVERAGE
          TIME_STANDARD_DEVIATION-VAL
          TIME_STANDARD_DEVIATION
          DISTANCE_AVERAGE-VAL
          DISTANCE_AVERAGE
          VELOCITY_AVERAGE-VAL
          VELOCITY_AVERAGE
          LINEAR_VELOCITY_AVERAGE-VAL
          LINEAR_VELOCITY_AVERAGE
          MAXIMUM_LINEAR_VELOCITY-VAL
          MAXIMUM_LINEAR_VELOCITY
          DENSITY-VAL
          DENSITY
          MAX_OBSTACLE_SHIFTMENT-VAL
          MAX_OBSTACLE_SHIFTMENT
          OBSTACLE_LENGTH-VAL
          OBSTACLE_LENGTH
          FAILURES-VAL
          FAILURES
))