(cl:in-package costum_msgs-msg)
(cl:export '(SEGMENT_INDEX-VAL
          SEGMENT_INDEX
          INITIAL_POINT-VAL
          INITIAL_POINT
          END_POINT-VAL
          END_POINT
          DISTANCE_BETWEEN_OBSTACLES-VAL
          DISTANCE_BETWEEN_OBSTACLES
          SEGMENT_SIMULATION_TIMEOUT-VAL
          SEGMENT_SIMULATION_TIMEOUT
))