(cl:in-package costum_msgs-msg)
(cl:export '(METADATA-VAL
          METADATA
          GLOBAL_SIMULATION_RESULTS-VAL
          GLOBAL_SIMULATION_RESULTS
          GLOBAL_SEGMENTS_RESULTS-VAL
          GLOBAL_SEGMENTS_RESULTS
          INDIVIDUAL_ITERATIONS_RESULTS-VAL
          INDIVIDUAL_ITERATIONS_RESULTS
))