(cl:defpackage costum_msgs-msg
  (:use )
  (:export
   "<GLOBALSEGMENTRESULTSMSG>"
   "GLOBALSEGMENTRESULTSMSG"
   "<GLOBALSIMULATIONRESULTSMSG>"
   "GLOBALSIMULATIONRESULTSMSG"
   "<INDIVIDUALITERATIONRESULTSMSG>"
   "INDIVIDUALITERATIONRESULTSMSG"
   "<INDIVIDUALSEGMENTRESULTSMSG>"
   "INDIVIDUALSEGMENTRESULTSMSG"
   "<SEGMENTMETADATAMSG>"
   "SEGMENTMETADATAMSG"
   "<SEGMENTSMETADATAMSG>"
   "SEGMENTSMETADATAMSG"
   "<SIMULATIONMETADATAMSG>"
   "SIMULATIONMETADATAMSG"
   "<SIMULATIONMSG>"
   "SIMULATIONMSG"
  ))

