// Generated by gencpp from file costum_msgs/IndividualSegmentResultsMsg.msg
// DO NOT EDIT!


#ifndef COSTUM_MSGS_MESSAGE_INDIVIDUALSEGMENTRESULTSMSG_H
#define COSTUM_MSGS_MESSAGE_INDIVIDUALSEGMENTRESULTSMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace costum_msgs
{
template <class ContainerAllocator>
struct IndividualSegmentResultsMsg_
{
  typedef IndividualSegmentResultsMsg_<ContainerAllocator> Type;

  IndividualSegmentResultsMsg_()
    : segment_index(0)
    , time(0.0)
    , distance(0.0)
    , speed(0.0)
    , failure(false)  {
    }
  IndividualSegmentResultsMsg_(const ContainerAllocator& _alloc)
    : segment_index(0)
    , time(0.0)
    , distance(0.0)
    , speed(0.0)
    , failure(false)  {
  (void)_alloc;
    }



   typedef int64_t _segment_index_type;
  _segment_index_type segment_index;

   typedef double _time_type;
  _time_type time;

   typedef double _distance_type;
  _distance_type distance;

   typedef double _speed_type;
  _speed_type speed;

   typedef uint8_t _failure_type;
  _failure_type failure;





  typedef boost::shared_ptr< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> const> ConstPtr;

}; // struct IndividualSegmentResultsMsg_

typedef ::costum_msgs::IndividualSegmentResultsMsg_<std::allocator<void> > IndividualSegmentResultsMsg;

typedef boost::shared_ptr< ::costum_msgs::IndividualSegmentResultsMsg > IndividualSegmentResultsMsgPtr;
typedef boost::shared_ptr< ::costum_msgs::IndividualSegmentResultsMsg const> IndividualSegmentResultsMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace costum_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'costum_msgs': ['/home/abiantorres/Documentos/tfg/autonomous-vehicles-system-simulation/low_level_simulation/src/costum_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8203f1ba3a513f2e426062e0f95d02d8";
  }

  static const char* value(const ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8203f1ba3a513f2eULL;
  static const uint64_t static_value2 = 0x426062e0f95d02d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costum_msgs/IndividualSegmentResultsMsg";
  }

  static const char* value(const ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 segment_index\n\
float64 time\n\
float64 distance\n\
float64 speed\n\
bool failure\n\
";
  }

  static const char* value(const ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.segment_index);
      stream.next(m.time);
      stream.next(m.distance);
      stream.next(m.speed);
      stream.next(m.failure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IndividualSegmentResultsMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costum_msgs::IndividualSegmentResultsMsg_<ContainerAllocator>& v)
  {
    s << indent << "segment_index: ";
    Printer<int64_t>::stream(s, indent + "  ", v.segment_index);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "failure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.failure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTUM_MSGS_MESSAGE_INDIVIDUALSEGMENTRESULTSMSG_H
