// Generated by gencpp from file costum_msgs/RouteTimes.msg
// DO NOT EDIT!


#ifndef COSTUM_MSGS_MESSAGE_ROUTETIMES_H
#define COSTUM_MSGS_MESSAGE_ROUTETIMES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace costum_msgs
{
template <class ContainerAllocator>
struct RouteTimes_
{
  typedef RouteTimes_<ContainerAllocator> Type;

  RouteTimes_()
    : times()  {
    }
  RouteTimes_(const ContainerAllocator& _alloc)
    : times(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _times_type;
  _times_type times;





  typedef boost::shared_ptr< ::costum_msgs::RouteTimes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costum_msgs::RouteTimes_<ContainerAllocator> const> ConstPtr;

}; // struct RouteTimes_

typedef ::costum_msgs::RouteTimes_<std::allocator<void> > RouteTimes;

typedef boost::shared_ptr< ::costum_msgs::RouteTimes > RouteTimesPtr;
typedef boost::shared_ptr< ::costum_msgs::RouteTimes const> RouteTimesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costum_msgs::RouteTimes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costum_msgs::RouteTimes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace costum_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'costum_msgs': ['/home/parallels/tfg/autonomous-vehicles-system-simulation/low_level_simulation/src/costum_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::costum_msgs::RouteTimes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costum_msgs::RouteTimes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costum_msgs::RouteTimes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costum_msgs::RouteTimes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costum_msgs::RouteTimes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costum_msgs::RouteTimes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costum_msgs::RouteTimes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d394ee177c216ecab30a68521290c92";
  }

  static const char* value(const ::costum_msgs::RouteTimes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d394ee177c216ecULL;
  static const uint64_t static_value2 = 0xab30a68521290c92ULL;
};

template<class ContainerAllocator>
struct DataType< ::costum_msgs::RouteTimes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costum_msgs/RouteTimes";
  }

  static const char* value(const ::costum_msgs::RouteTimes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costum_msgs::RouteTimes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] times\n\
";
  }

  static const char* value(const ::costum_msgs::RouteTimes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costum_msgs::RouteTimes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.times);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RouteTimes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costum_msgs::RouteTimes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costum_msgs::RouteTimes_<ContainerAllocator>& v)
  {
    s << indent << "times[]" << std::endl;
    for (size_t i = 0; i < v.times.size(); ++i)
    {
      s << indent << "  times[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.times[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTUM_MSGS_MESSAGE_ROUTETIMES_H
