// Generated by gencpp from file costum_msgs/SimulationMetadataMsg.msg
// DO NOT EDIT!


#ifndef COSTUM_MSGS_MESSAGE_SIMULATIONMETADATAMSG_H
#define COSTUM_MSGS_MESSAGE_SIMULATIONMETADATAMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <costum_msgs/SegmentsMetadataMsg.h>

namespace costum_msgs
{
template <class ContainerAllocator>
struct SimulationMetadataMsg_
{
  typedef SimulationMetadataMsg_<ContainerAllocator> Type;

  SimulationMetadataMsg_()
    : simulation_hash()
    , robot_file()
    , world_file()
    , plan_file()
    , map_file()
    , date()
    , n_segments(0)
    , segments_metadata()
    , n_iterations(0)
    , timeout_factor(0)
    , useful_simulation(false)
    , local_planner()
    , global_planner()  {
    }
  SimulationMetadataMsg_(const ContainerAllocator& _alloc)
    : simulation_hash(_alloc)
    , robot_file(_alloc)
    , world_file(_alloc)
    , plan_file(_alloc)
    , map_file(_alloc)
    , date(_alloc)
    , n_segments(0)
    , segments_metadata(_alloc)
    , n_iterations(0)
    , timeout_factor(0)
    , useful_simulation(false)
    , local_planner(_alloc)
    , global_planner(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _simulation_hash_type;
  _simulation_hash_type simulation_hash;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_file_type;
  _robot_file_type robot_file;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _world_file_type;
  _world_file_type world_file;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _plan_file_type;
  _plan_file_type plan_file;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _map_file_type;
  _map_file_type map_file;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _date_type;
  _date_type date;

   typedef int64_t _n_segments_type;
  _n_segments_type n_segments;

   typedef  ::costum_msgs::SegmentsMetadataMsg_<ContainerAllocator>  _segments_metadata_type;
  _segments_metadata_type segments_metadata;

   typedef int64_t _n_iterations_type;
  _n_iterations_type n_iterations;

   typedef int64_t _timeout_factor_type;
  _timeout_factor_type timeout_factor;

   typedef uint8_t _useful_simulation_type;
  _useful_simulation_type useful_simulation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _local_planner_type;
  _local_planner_type local_planner;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _global_planner_type;
  _global_planner_type global_planner;





  typedef boost::shared_ptr< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SimulationMetadataMsg_

typedef ::costum_msgs::SimulationMetadataMsg_<std::allocator<void> > SimulationMetadataMsg;

typedef boost::shared_ptr< ::costum_msgs::SimulationMetadataMsg > SimulationMetadataMsgPtr;
typedef boost::shared_ptr< ::costum_msgs::SimulationMetadataMsg const> SimulationMetadataMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace costum_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'costum_msgs': ['/home/abiantorres/Documentos/tfg/autonomous-vehicles-system-simulation/low_level_simulation/src/costum_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b64b7db80c218e4a90f09816c189d51c";
  }

  static const char* value(const ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb64b7db80c218e4aULL;
  static const uint64_t static_value2 = 0x90f09816c189d51cULL;
};

template<class ContainerAllocator>
struct DataType< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costum_msgs/SimulationMetadataMsg";
  }

  static const char* value(const ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string simulation_hash\n\
string robot_file\n\
string world_file\n\
string plan_file\n\
string map_file\n\
string date\n\
int64 n_segments\n\
SegmentsMetadataMsg segments_metadata\n\
int64 n_iterations\n\
int64 timeout_factor\n\
bool useful_simulation\n\
string local_planner\n\
string global_planner\n\
\n\
================================================================================\n\
MSG: costum_msgs/SegmentsMetadataMsg\n\
SegmentMetadataMsg[] segments_metadata\n\
\n\
================================================================================\n\
MSG: costum_msgs/SegmentMetadataMsg\n\
int64 segment_index\n\
geometry_msgs/Point initial_point\n\
geometry_msgs/Point end_point\n\
float64 distance_between_obstacles\n\
int64 segment_simulation_timeout\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.simulation_hash);
      stream.next(m.robot_file);
      stream.next(m.world_file);
      stream.next(m.plan_file);
      stream.next(m.map_file);
      stream.next(m.date);
      stream.next(m.n_segments);
      stream.next(m.segments_metadata);
      stream.next(m.n_iterations);
      stream.next(m.timeout_factor);
      stream.next(m.useful_simulation);
      stream.next(m.local_planner);
      stream.next(m.global_planner);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimulationMetadataMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costum_msgs::SimulationMetadataMsg_<ContainerAllocator>& v)
  {
    s << indent << "simulation_hash: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.simulation_hash);
    s << indent << "robot_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_file);
    s << indent << "world_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.world_file);
    s << indent << "plan_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plan_file);
    s << indent << "map_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_file);
    s << indent << "date: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.date);
    s << indent << "n_segments: ";
    Printer<int64_t>::stream(s, indent + "  ", v.n_segments);
    s << indent << "segments_metadata: ";
    s << std::endl;
    Printer< ::costum_msgs::SegmentsMetadataMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.segments_metadata);
    s << indent << "n_iterations: ";
    Printer<int64_t>::stream(s, indent + "  ", v.n_iterations);
    s << indent << "timeout_factor: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timeout_factor);
    s << indent << "useful_simulation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.useful_simulation);
    s << indent << "local_planner: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.local_planner);
    s << indent << "global_planner: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.global_planner);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTUM_MSGS_MESSAGE_SIMULATIONMETADATAMSG_H
