# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from costum_msgs/GoalInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GoalInfo(genpy.Message):
  _md5sum = "5c2161efb882ab714cdc912beb12392f"
  _type = "costum_msgs/GoalInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x_position
float64 y_position
float64 z_position
float64 x_orientation
float64 y_orientation
float64 z_orientation
float64 w_orientation
float64 time
"""
  __slots__ = ['x_position','y_position','z_position','x_orientation','y_orientation','z_orientation','w_orientation','time']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_position,y_position,z_position,x_orientation,y_orientation,z_orientation,w_orientation,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GoalInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x_position is None:
        self.x_position = 0.
      if self.y_position is None:
        self.y_position = 0.
      if self.z_position is None:
        self.z_position = 0.
      if self.x_orientation is None:
        self.x_orientation = 0.
      if self.y_orientation is None:
        self.y_orientation = 0.
      if self.z_orientation is None:
        self.z_orientation = 0.
      if self.w_orientation is None:
        self.w_orientation = 0.
      if self.time is None:
        self.time = 0.
    else:
      self.x_position = 0.
      self.y_position = 0.
      self.z_position = 0.
      self.x_orientation = 0.
      self.y_orientation = 0.
      self.z_orientation = 0.
      self.w_orientation = 0.
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.x_position, _x.y_position, _x.z_position, _x.x_orientation, _x.y_orientation, _x.z_orientation, _x.w_orientation, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.x_position, _x.y_position, _x.z_position, _x.x_orientation, _x.y_orientation, _x.z_orientation, _x.w_orientation, _x.time,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.x_position, _x.y_position, _x.z_position, _x.x_orientation, _x.y_orientation, _x.z_orientation, _x.w_orientation, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.x_position, _x.y_position, _x.z_position, _x.x_orientation, _x.y_orientation, _x.z_orientation, _x.w_orientation, _x.time,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
