# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from costum_msgs/SimulationMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import costum_msgs.msg
import geometry_msgs.msg

class SimulationMsg(genpy.Message):
  _md5sum = "1fc04017a8937851069ea4d1e0d47bfe"
  _type = "costum_msgs/SimulationMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """SimulationMetadataMsg metadata
GlobalSimulationResultsMsg global_simulation_results
GlobalSegmentResultsMsg[] global_segments_results
IndividualIterationResultsMsg[] individual_iterations_results

================================================================================
MSG: costum_msgs/SimulationMetadataMsg
string simulation_hash
string robot_file
string world_file
string plan_file
string map_file
string date
int64 n_segments
SegmentsMetadataMsg segments_metadata
int64 n_iterations
int64 timeout_factor
bool useful_simulation
string local_planner
string global_planner

================================================================================
MSG: costum_msgs/SegmentsMetadataMsg
SegmentMetadataMsg[] segments_metadata

================================================================================
MSG: costum_msgs/SegmentMetadataMsg
int64 segment_index
geometry_msgs/Point initial_point
geometry_msgs/Point end_point
float64 distance_between_obstacles
int64 segment_simulation_timeout

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: costum_msgs/GlobalSimulationResultsMsg
int64 n_failures
float64 time_mean
float64 time_stdev
float64 time_max
float64 time_min
float64 distance_mean
float64 distance_stdev
float64 distance_max
float64 distance_min
float64 speed_mean
float64 speed_stdev
float64 speed_max
float64 speed_min

================================================================================
MSG: costum_msgs/GlobalSegmentResultsMsg
int64 segment_index
int64 n_failures
float64 time_mean
float64 time_stdev
float64 time_max
float64 time_min
float64 distance_mean
float64 distance_stdev
float64 distance_max
float64 distance_min
float64 speed_mean
float64 speed_stdev
float64 speed_max
float64 speed_min

================================================================================
MSG: costum_msgs/IndividualIterationResultsMsg
int64 iteration_index
bool failure
int64 failure_segment_index
float64 time
float64 distance
float64 speed
IndividualSegmentResultsMsg[] segments_results

================================================================================
MSG: costum_msgs/IndividualSegmentResultsMsg
int64 segment_index
float64 time
float64 distance
float64 speed
bool failure
"""
  __slots__ = ['metadata','global_simulation_results','global_segments_results','individual_iterations_results']
  _slot_types = ['costum_msgs/SimulationMetadataMsg','costum_msgs/GlobalSimulationResultsMsg','costum_msgs/GlobalSegmentResultsMsg[]','costum_msgs/IndividualIterationResultsMsg[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       metadata,global_simulation_results,global_segments_results,individual_iterations_results

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SimulationMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.metadata is None:
        self.metadata = costum_msgs.msg.SimulationMetadataMsg()
      if self.global_simulation_results is None:
        self.global_simulation_results = costum_msgs.msg.GlobalSimulationResultsMsg()
      if self.global_segments_results is None:
        self.global_segments_results = []
      if self.individual_iterations_results is None:
        self.individual_iterations_results = []
    else:
      self.metadata = costum_msgs.msg.SimulationMetadataMsg()
      self.global_simulation_results = costum_msgs.msg.GlobalSimulationResultsMsg()
      self.global_segments_results = []
      self.individual_iterations_results = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.metadata.simulation_hash
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.robot_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.world_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.plan_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.map_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.date
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_q().pack(self.metadata.n_segments))
      length = len(self.metadata.segments_metadata.segments_metadata)
      buff.write(_struct_I.pack(length))
      for val1 in self.metadata.segments_metadata.segments_metadata:
        buff.write(_get_struct_q().pack(val1.segment_index))
        _v1 = val1.initial_point
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.end_point
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_dq().pack(_x.distance_between_obstacles, _x.segment_simulation_timeout))
      _x = self
      buff.write(_get_struct_2qB().pack(_x.metadata.n_iterations, _x.metadata.timeout_factor, _x.metadata.useful_simulation))
      _x = self.metadata.local_planner
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.global_planner
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_q12d().pack(_x.global_simulation_results.n_failures, _x.global_simulation_results.time_mean, _x.global_simulation_results.time_stdev, _x.global_simulation_results.time_max, _x.global_simulation_results.time_min, _x.global_simulation_results.distance_mean, _x.global_simulation_results.distance_stdev, _x.global_simulation_results.distance_max, _x.global_simulation_results.distance_min, _x.global_simulation_results.speed_mean, _x.global_simulation_results.speed_stdev, _x.global_simulation_results.speed_max, _x.global_simulation_results.speed_min))
      length = len(self.global_segments_results)
      buff.write(_struct_I.pack(length))
      for val1 in self.global_segments_results:
        _x = val1
        buff.write(_get_struct_2q12d().pack(_x.segment_index, _x.n_failures, _x.time_mean, _x.time_stdev, _x.time_max, _x.time_min, _x.distance_mean, _x.distance_stdev, _x.distance_max, _x.distance_min, _x.speed_mean, _x.speed_stdev, _x.speed_max, _x.speed_min))
      length = len(self.individual_iterations_results)
      buff.write(_struct_I.pack(length))
      for val1 in self.individual_iterations_results:
        _x = val1
        buff.write(_get_struct_qBq3d().pack(_x.iteration_index, _x.failure, _x.failure_segment_index, _x.time, _x.distance, _x.speed))
        length = len(val1.segments_results)
        buff.write(_struct_I.pack(length))
        for val2 in val1.segments_results:
          _x = val2
          buff.write(_get_struct_q3dB().pack(_x.segment_index, _x.time, _x.distance, _x.speed, _x.failure))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.metadata is None:
        self.metadata = costum_msgs.msg.SimulationMetadataMsg()
      if self.global_simulation_results is None:
        self.global_simulation_results = costum_msgs.msg.GlobalSimulationResultsMsg()
      if self.global_segments_results is None:
        self.global_segments_results = None
      if self.individual_iterations_results is None:
        self.individual_iterations_results = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.simulation_hash = str[start:end].decode('utf-8')
      else:
        self.metadata.simulation_hash = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.robot_file = str[start:end].decode('utf-8')
      else:
        self.metadata.robot_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.world_file = str[start:end].decode('utf-8')
      else:
        self.metadata.world_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.plan_file = str[start:end].decode('utf-8')
      else:
        self.metadata.plan_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.map_file = str[start:end].decode('utf-8')
      else:
        self.metadata.map_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.date = str[start:end].decode('utf-8')
      else:
        self.metadata.date = str[start:end]
      start = end
      end += 8
      (self.metadata.n_segments,) = _get_struct_q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.metadata.segments_metadata.segments_metadata = []
      for i in range(0, length):
        val1 = costum_msgs.msg.SegmentMetadataMsg()
        start = end
        end += 8
        (val1.segment_index,) = _get_struct_q().unpack(str[start:end])
        _v3 = val1.initial_point
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.end_point
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 16
        (_x.distance_between_obstacles, _x.segment_simulation_timeout,) = _get_struct_dq().unpack(str[start:end])
        self.metadata.segments_metadata.segments_metadata.append(val1)
      _x = self
      start = end
      end += 17
      (_x.metadata.n_iterations, _x.metadata.timeout_factor, _x.metadata.useful_simulation,) = _get_struct_2qB().unpack(str[start:end])
      self.metadata.useful_simulation = bool(self.metadata.useful_simulation)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.local_planner = str[start:end].decode('utf-8')
      else:
        self.metadata.local_planner = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.global_planner = str[start:end].decode('utf-8')
      else:
        self.metadata.global_planner = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.global_simulation_results.n_failures, _x.global_simulation_results.time_mean, _x.global_simulation_results.time_stdev, _x.global_simulation_results.time_max, _x.global_simulation_results.time_min, _x.global_simulation_results.distance_mean, _x.global_simulation_results.distance_stdev, _x.global_simulation_results.distance_max, _x.global_simulation_results.distance_min, _x.global_simulation_results.speed_mean, _x.global_simulation_results.speed_stdev, _x.global_simulation_results.speed_max, _x.global_simulation_results.speed_min,) = _get_struct_q12d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.global_segments_results = []
      for i in range(0, length):
        val1 = costum_msgs.msg.GlobalSegmentResultsMsg()
        _x = val1
        start = end
        end += 112
        (_x.segment_index, _x.n_failures, _x.time_mean, _x.time_stdev, _x.time_max, _x.time_min, _x.distance_mean, _x.distance_stdev, _x.distance_max, _x.distance_min, _x.speed_mean, _x.speed_stdev, _x.speed_max, _x.speed_min,) = _get_struct_2q12d().unpack(str[start:end])
        self.global_segments_results.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.individual_iterations_results = []
      for i in range(0, length):
        val1 = costum_msgs.msg.IndividualIterationResultsMsg()
        _x = val1
        start = end
        end += 41
        (_x.iteration_index, _x.failure, _x.failure_segment_index, _x.time, _x.distance, _x.speed,) = _get_struct_qBq3d().unpack(str[start:end])
        val1.failure = bool(val1.failure)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.segments_results = []
        for i in range(0, length):
          val2 = costum_msgs.msg.IndividualSegmentResultsMsg()
          _x = val2
          start = end
          end += 33
          (_x.segment_index, _x.time, _x.distance, _x.speed, _x.failure,) = _get_struct_q3dB().unpack(str[start:end])
          val2.failure = bool(val2.failure)
          val1.segments_results.append(val2)
        self.individual_iterations_results.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.metadata.simulation_hash
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.robot_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.world_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.plan_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.map_file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.date
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_q().pack(self.metadata.n_segments))
      length = len(self.metadata.segments_metadata.segments_metadata)
      buff.write(_struct_I.pack(length))
      for val1 in self.metadata.segments_metadata.segments_metadata:
        buff.write(_get_struct_q().pack(val1.segment_index))
        _v5 = val1.initial_point
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.end_point
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_dq().pack(_x.distance_between_obstacles, _x.segment_simulation_timeout))
      _x = self
      buff.write(_get_struct_2qB().pack(_x.metadata.n_iterations, _x.metadata.timeout_factor, _x.metadata.useful_simulation))
      _x = self.metadata.local_planner
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.metadata.global_planner
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_q12d().pack(_x.global_simulation_results.n_failures, _x.global_simulation_results.time_mean, _x.global_simulation_results.time_stdev, _x.global_simulation_results.time_max, _x.global_simulation_results.time_min, _x.global_simulation_results.distance_mean, _x.global_simulation_results.distance_stdev, _x.global_simulation_results.distance_max, _x.global_simulation_results.distance_min, _x.global_simulation_results.speed_mean, _x.global_simulation_results.speed_stdev, _x.global_simulation_results.speed_max, _x.global_simulation_results.speed_min))
      length = len(self.global_segments_results)
      buff.write(_struct_I.pack(length))
      for val1 in self.global_segments_results:
        _x = val1
        buff.write(_get_struct_2q12d().pack(_x.segment_index, _x.n_failures, _x.time_mean, _x.time_stdev, _x.time_max, _x.time_min, _x.distance_mean, _x.distance_stdev, _x.distance_max, _x.distance_min, _x.speed_mean, _x.speed_stdev, _x.speed_max, _x.speed_min))
      length = len(self.individual_iterations_results)
      buff.write(_struct_I.pack(length))
      for val1 in self.individual_iterations_results:
        _x = val1
        buff.write(_get_struct_qBq3d().pack(_x.iteration_index, _x.failure, _x.failure_segment_index, _x.time, _x.distance, _x.speed))
        length = len(val1.segments_results)
        buff.write(_struct_I.pack(length))
        for val2 in val1.segments_results:
          _x = val2
          buff.write(_get_struct_q3dB().pack(_x.segment_index, _x.time, _x.distance, _x.speed, _x.failure))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.metadata is None:
        self.metadata = costum_msgs.msg.SimulationMetadataMsg()
      if self.global_simulation_results is None:
        self.global_simulation_results = costum_msgs.msg.GlobalSimulationResultsMsg()
      if self.global_segments_results is None:
        self.global_segments_results = None
      if self.individual_iterations_results is None:
        self.individual_iterations_results = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.simulation_hash = str[start:end].decode('utf-8')
      else:
        self.metadata.simulation_hash = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.robot_file = str[start:end].decode('utf-8')
      else:
        self.metadata.robot_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.world_file = str[start:end].decode('utf-8')
      else:
        self.metadata.world_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.plan_file = str[start:end].decode('utf-8')
      else:
        self.metadata.plan_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.map_file = str[start:end].decode('utf-8')
      else:
        self.metadata.map_file = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.date = str[start:end].decode('utf-8')
      else:
        self.metadata.date = str[start:end]
      start = end
      end += 8
      (self.metadata.n_segments,) = _get_struct_q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.metadata.segments_metadata.segments_metadata = []
      for i in range(0, length):
        val1 = costum_msgs.msg.SegmentMetadataMsg()
        start = end
        end += 8
        (val1.segment_index,) = _get_struct_q().unpack(str[start:end])
        _v7 = val1.initial_point
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.end_point
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 16
        (_x.distance_between_obstacles, _x.segment_simulation_timeout,) = _get_struct_dq().unpack(str[start:end])
        self.metadata.segments_metadata.segments_metadata.append(val1)
      _x = self
      start = end
      end += 17
      (_x.metadata.n_iterations, _x.metadata.timeout_factor, _x.metadata.useful_simulation,) = _get_struct_2qB().unpack(str[start:end])
      self.metadata.useful_simulation = bool(self.metadata.useful_simulation)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.local_planner = str[start:end].decode('utf-8')
      else:
        self.metadata.local_planner = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata.global_planner = str[start:end].decode('utf-8')
      else:
        self.metadata.global_planner = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.global_simulation_results.n_failures, _x.global_simulation_results.time_mean, _x.global_simulation_results.time_stdev, _x.global_simulation_results.time_max, _x.global_simulation_results.time_min, _x.global_simulation_results.distance_mean, _x.global_simulation_results.distance_stdev, _x.global_simulation_results.distance_max, _x.global_simulation_results.distance_min, _x.global_simulation_results.speed_mean, _x.global_simulation_results.speed_stdev, _x.global_simulation_results.speed_max, _x.global_simulation_results.speed_min,) = _get_struct_q12d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.global_segments_results = []
      for i in range(0, length):
        val1 = costum_msgs.msg.GlobalSegmentResultsMsg()
        _x = val1
        start = end
        end += 112
        (_x.segment_index, _x.n_failures, _x.time_mean, _x.time_stdev, _x.time_max, _x.time_min, _x.distance_mean, _x.distance_stdev, _x.distance_max, _x.distance_min, _x.speed_mean, _x.speed_stdev, _x.speed_max, _x.speed_min,) = _get_struct_2q12d().unpack(str[start:end])
        self.global_segments_results.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.individual_iterations_results = []
      for i in range(0, length):
        val1 = costum_msgs.msg.IndividualIterationResultsMsg()
        _x = val1
        start = end
        end += 41
        (_x.iteration_index, _x.failure, _x.failure_segment_index, _x.time, _x.distance, _x.speed,) = _get_struct_qBq3d().unpack(str[start:end])
        val1.failure = bool(val1.failure)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.segments_results = []
        for i in range(0, length):
          val2 = costum_msgs.msg.IndividualSegmentResultsMsg()
          _x = val2
          start = end
          end += 33
          (_x.segment_index, _x.time, _x.distance, _x.speed, _x.failure,) = _get_struct_q3dB().unpack(str[start:end])
          val2.failure = bool(val2.failure)
          val1.segments_results.append(val2)
        self.individual_iterations_results.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q3dB = None
def _get_struct_q3dB():
    global _struct_q3dB
    if _struct_q3dB is None:
        _struct_q3dB = struct.Struct("<q3dB")
    return _struct_q3dB
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_q = None
def _get_struct_q():
    global _struct_q
    if _struct_q is None:
        _struct_q = struct.Struct("<q")
    return _struct_q
_struct_2qB = None
def _get_struct_2qB():
    global _struct_2qB
    if _struct_2qB is None:
        _struct_2qB = struct.Struct("<2qB")
    return _struct_2qB
_struct_2q12d = None
def _get_struct_2q12d():
    global _struct_2q12d
    if _struct_2q12d is None:
        _struct_2q12d = struct.Struct("<2q12d")
    return _struct_2q12d
_struct_q12d = None
def _get_struct_q12d():
    global _struct_q12d
    if _struct_q12d is None:
        _struct_q12d = struct.Struct("<q12d")
    return _struct_q12d
_struct_qBq3d = None
def _get_struct_qBq3d():
    global _struct_qBq3d
    if _struct_qBq3d is None:
        _struct_qBq3d = struct.Struct("<qBq3d")
    return _struct_qBq3d
_struct_dq = None
def _get_struct_dq():
    global _struct_dq
    if _struct_dq is None:
        _struct_dq = struct.Struct("<dq")
    return _struct_dq
